# Generated by Django 4.2.5 on 2023-09-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_coin_exchange_network_created_at_network_updated_at_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCryptoWallet',
            fields=[
                ('current_balance', models.BigIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_crypto', to='coin.coin', verbose_name='coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cryptos', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user crypto',
                'verbose_name_plural': 'user cryptos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user wallet',
                'verbose_name_plural': 'user wallets',
            },
        ),
        migrations.CreateModel(
            name='UserWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.BigIntegerField(default=0)),
                ('total_balance', models.BigIntegerField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.userwallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'user wallet transaction',
            },
        ),
        migrations.CreateModel(
            name='UserCryptoWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.BigIntegerField(default=0)),
                ('total_balance', models.BigIntegerField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.usercryptowallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'user crypto wallet transaction',
            },
        ),
    ]
