# Generated by Django 4.2.5 on 2023-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'init'), (1, 'waiting for send to exchange'), (2, 'send to exchange'), (3, 'retry to send to exchange'), (4, 'success'), (5, 'failed')], db_index=True, default=0, editable=False, verbose_name='status of order'),
        ),
    ]
