# Generated by Django 4.2.5 on 2023-09-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_exchangesite'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='exchange.exchangesite'),
        ),
    ]
