# Generated by Django 4.2.5 on 2023-09-30 22:05

import apps.coin.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='symbol')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.coin.models.get_coin_image, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'coin',
                'verbose_name_plural': 'coins',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
            },
        ),
    ]
