# Generated by Django 4.2.5 on 2023-10-01 13:45

import apps.coin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='symbol')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.coin.models.get_coin_image, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'coin',
                'verbose_name_plural': 'coins',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
            },
        ),
    ]
