# Generated by Django 4.2.5 on 2023-09-30 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='symbol')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'coin',
                'verbose_name_plural': 'coins',
            },
        ),
    ]
