# Generated by Django 4.2.5 on 2023-10-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='exchange.exchangesite'),
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='coin.network'),
        ),
    ]
