# Generated by Django 4.2.5 on 2023-09-30 12:15

import apps.coin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='price',
        ),
        migrations.AddField(
            model_name='coin',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.coin.models.get_coin_image, verbose_name='icon'),
        ),
    ]
