# Generated by Django 4.2.5 on 2023-10-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_order_transfer_tax_order_transfer_fee_and_more'),
        ('coin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='exchange.exchangesite'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='coin.network'),
        ),
    ]
