# Generated by Django 4.2.5 on 2023-09-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_remove_coin_price_coin_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'network',
                'verbose_name_plural': 'networks',
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='coins', to='coin.network'),
            preserve_default=False,
        ),
    ]
